'use strict';
// ─── Arte: todos los sprites escritos como texto (un carácter = un píxel) ───
// Cada sprite tiene su paleta. Las letras de G.GLOW brillan en la oscuridad (mapa emisivo).
G.ART = {};
G.GLOW = 'cCxXeE';

// ── el protagonista (sin marcas) ──
const PAL_PROTA = {
  k: '#0a1520', n: '#122636', d: '#1b3a4a', t: '#265c6a', T: '#3a8a94',
  w: '#eef2f0', W: '#c2ccd0', g: '#7c8a94',
  c: '#86ffdc', C: '#3cc4a4',
  y: '#c9b59e', b: '#9a8676', B: '#6a5a50', p: '#4a3a3e',
};
G.PAL_PROTA = PAL_PROTA;

G.ART.prota_down = { pal: PAL_PROTA, rows: [
  '...k.............k....',
  '..kkk...........kkk...',
  '..knk...........knk...',
  '..kndk.........kdnk...',
  '..kndpk.......kpdnk...',
  '..kTdpdkkkkkkkdpdTk...',
  '..kTnnnnnnnnnnnnnTk...',
  '..knnnnnnnnnnnnnnnk...',
  '.kdnnwwwwnnnnwwwwnndk.',
  'kCdnwwwwwwnnwwwwwwndCk',
  'kCnwwkkkwwwwwwkkkwwnCk',
  'kcnwkcckwwwwwwkcckwnck',
  '.kCwwkkwwwwwwwwkkwwCk.',
  '..kwwwwwwwkkwwwwwwwk..',
  '..kWwwwwwwwkwwwwwwWk..',
  '...kWWwwwwwwwwwwWWk...',
  '....kkWWWwwwwWWWkk....',
  '...kbbkkkkkkkkkkbbk...',
  '..kbyybbbbbbbbbbyybk..',
  '..kBbbyyyyyyyyyybbBk..',
  '.knkBBbbbkbbkbbbBkndk.',
  '.knnkktdddtdddtkkndk..',
  '.knnnktddTtTddtknnnk..',
  '.knnnktddttdddtknnnk..',
  '.knnnktdddtTddtknnnk..',
  '.knnnktddTtdddtknnnk..',
  '.kCCnktdddtTddtknCCk..',
  '.kbbCktddTtdddtkCbbk..',
  '.kbbkkttdddddttkkbbk..',
  '..kknnkttdddttknnkk.kk',
  '...knnnkkttttkknnnkkCk',
  '...knnnnkkkkkknnnnkcCk',
  '...knnnnk..knnnnkkdCk.',
  '...knnnnk..knnnnkddk..',
  '...knnnk....knnnkdk...',
  '...kCCck....kcCCkk....',
  '....kkk......kkk......',
] };

G.ART.prota_up = { pal: PAL_PROTA, rows: [
  '...k.............k....',
  '..kkk...........kkk...',
  '..knk...........knk...',
  '..kndk.........kdnk...',
  '..knddk.......kddnk...',
  '..kTdddkkkkkkkdddTk...',
  '..kTnnnnnnnnnnnnnTk...',
  '..knnnnnnnnnnnnnnnk...',
  '.kdnnnnnnnnnnnnnnndk..',
  'kCdnnnnnnnnnnnnnnndCk.',
  'kCnnnnnnnnnnnnnnnnnCk.',
  'kcnnnnnnnnnnnnnnnnnck.',
  '.kCnnnnnnnnnnnnnnnCk..',
  '..kdnnnnnnnnnnnnndk...',
  '..kddnnnnnnnnnnnddk...',
  '...kddnnnnnnnnnddk....',
  '....kkdddddddddkk.....',
  '...kbbkkkkkkkkkbbk....',
  '..kbyybbbbbbbbbyybk...',
  '..kBbbyyybyyyyybbBk...',
  '.knkBBbbkbbkbbbBknk...',
  '.knnkknnkbbknnnkknk...',
  '.knnnknnkbykdnnknnk...',
  '.knnnknnnkbkdnnknnk...',
  '.knnnknnnkkkdnnknnk...',
  '.knnnknnnnnddnnknnk...',
  '.kCCnknnnnnddnnknCCk..',
  '.kbbCknnnnnddnnkCbbk..',
  '.kbbkknnnnkkkknkkbbk..',
  '..kknnknnkCCdkknkk....',
  '...knnnkkkcCdkkk......',
  '...knnnnk.kcdk.nk.....',
  '...knnnnk..kkknnk.....',
  '...knnnnk..knnnnk.....',
  '...knnnk....knnnk.....',
  '...kdddk....kdddk.....',
  '....kkk......kkk......',
] };

G.ART.prota_side = { pal: PAL_PROTA, rows: [
  '.......k..............',
  '......kkk.............',
  '......knk..k..........',
  '.....kndk.kk..........',
  '.....kndpkkdk.........',
  '.....kTdpdkdk.........',
  '....kTnnnnnnnk........',
  '...knnnnnnnnnnk.......',
  '..kdnnnnnnwwwwwk......',
  '.kCdnnnnnwwwwwwwk.....',
  'kCnnnnnnwwkkkwwwwk....',
  'kcnnnnnnwkcckwwwwwkk..',
  '.kCnnnnnwwkkwwwwwwwk..',
  '..kdnnnnwwwwwwwwwwk...',
  '..kddnnnWwwwwwwwkk....',
  '...kddnnnWWwwWWk......',
  '....kkdnnnkkkkk.......',
  '.kkbbkkkkkkkbbk.......',
  'kbybbkbyybbbyybk......',
  'kbbBkkbbyyyyybBk......',
  '.kkk.knkBBbbbBkk......',
  '.....knnkkdtdttk......',
  '.....knnnktdTtdk......',
  '.....knnnktddtdk......',
  '.....knnnktdTtdk......',
  '...kknnnnktddtdk......',
  '..kCknnCCktdTtdk......',
  '.kcCknkbbCtddtdk......',
  '.kCdkkkbbkttttkk......',
  '..kddknnkkkkkkk.......',
  '...kddknnnnnnk........',
  '....kkknnnnnnk........',
  '......knnk.knnk.......',
  '......knnk.knnnk......',
  '......knnk..knnk......',
  '......kCCCk.kcCCk.....',
  '.......kkkk..kkkk.....',
] };

// ── la planta-alma (punto de guardado): dormida y despierta ──
const PAL_PLANTA = {
  k: '#0a1418', g: '#1e4a3c', G: '#2f7a5a', l: '#4fae7a', p: '#b8c8d8', P: '#e6eef6', v: '#6a5a8a',
  c: '#dcfff4', C: '#7affd8', x: '#a8fff0',
};
G.ART.planta = { pal: PAL_PLANTA, rows: [
  '......kk......',
  '....kkPPkk....',
  '...kPpCCpPk...',
  '..kPpCccCpPk..',
  '..kpCcxxcCpk..',
  '..kpCcxxcCpk..',
  '..kPpCccCpPk..',
  '...kPpCCpPk...',
  '..kvkPppPkvk..',
  '.kvpvkkkkvpvk.',
  '.kvvk.kGk.kvvk',
  '..kk..kGk..kk.',
  '.kk...kGk...kk',
  'klGk..kGk..kGl',
  'kGlGk.kgk.kGlk',
  '.kGlGkkgkkGlk.',
  '..kkGGkgkGGk..',
  '....kkggGkk...',
  '...kgGlGGgk...',
  '..kkkkkkkkkk..',
] };
G.ART.planta_off = { pal: Object.assign({}, PAL_PLANTA, { c: '#6a7a88', C: '#4a5a68', x: '#8a9aa8' }), rows: G.ART.planta.rows };

// ── hongo luminoso ──
G.ART.hongo = { pal: { k: '#08121a', c: '#8afff0', C: '#3ac8c0', x: '#e0fffa', s: '#9aa8b0', S: '#5a6870' }, rows: [
  '...kkkk...',
  '..kCccCk..',
  '.kCcxxcCk.',
  'kCccxcccCk',
  'kkkCCCCkkk',
  '...ksSk...',
  '...ksSk...',
  '..kssSSk..',
] };
G.ART.hongos = { pal: G.ART.hongo.pal, rows: [
  '........kkk.....',
  '..kkkk.kCcCk....',
  '.kCccCkkcxcCk...',
  'kCcxxcCkCCCkk...',
  'kccxcccCksk.kkk.',
  'kkCCCCkk.sk.kcCk',
  '..ksSk...sk.kCCk',
  '..ksSk..kssk.sk.',
  '.kssSSk.kssk.sk.',
] };

// ── vegetación roja del pilar ──
G.ART.roja = { pal: { k: '#1a0610', r: '#c02a3a', R: '#7a1628', p: '#ff6a78', x: '#ff9aa8' }, rows: [
  '.....k......k...',
  '....kpk....kpk..',
  '..k.kpRk..kpRk..',
  '.kpkkRpk.kRpk.k.',
  '.kRpkRrkkrRk.kpk',
  '..kRrkRrrRk.kpRk',
  '.k.kRrrRrrkkpRk.',
  'kpk.kRrrRrkRrk..',
  'kRpkkRRrrrRrk...',
  '.kRrrkRRrRRk....',
  '..kkRRrRRkk.....',
  '....kkkkk.......',
] };
G.ART.roja_flor = { pal: { k: '#1a0610', r: '#c02a3a', R: '#7a1628', x: '#ffb0c0', X: '#ff5a78', g: '#5a1a28' }, rows: [
  '..kkk...',
  '.kXxXk..',
  'kXxxxXk.',
  'kXxxxXk.',
  '.kXXXk..',
  '..kgk...',
  '.kkgkk..',
  'kRkgkRk.',
  '.kRgRk..',
  '..kgk...',
] };

// ── farol de la tribu ──
G.ART.farol = { pal: { k: '#0c0a0e', b: '#5a4030', B: '#3a2a20', x: '#ffd88a', X: '#ffa850', o: '#c07a3a' }, rows: [
  '..kkkk..',
  '.kbbbbk.',
  '..kxxk..',
  '.kxXXxk.',
  '.kXxxXk.',
  '.kxXXxk.',
  '..kook..',
  '...kk...',
  '...bk...',
  '...bk...',
  '...bk...',
  '...bk...',
  '...bk...',
  '...bk...',
  '...bk...',
  '...Bk...',
  '...Bk...',
  '..kBBk..',
  '.kBBBBk.',
] };

// ── fragmento de memoria (objeto que flota) ──
G.ART.memoria = { pal: { k: '#1a1030', c: '#fff4d0', C: '#ffd070', x: '#ffffff' }, rows: [
  '...k...',
  '..kCk..',
  '.kCxCk.',
  'kCxcxCk',
  '.kCxCk.',
  '..kCk..',
  '...k...',
] };
