'use strict';
// ─── Zonas del Abismo ───
// Terreno:  # acantilado · = roca alta · - repisa · . roca · , musgo · : senda · r hierba roja · q cuarzo
//           ~ agua luminosa · _ sima · w madera · ^ roca roja · x cuarzo alto · s arena
// Objetos:  H hongo · K hongos · M hongo grande · A estalagmita · B roca · L farol · T tienda
//           S planta-alma · V hierba roja · F flor roja · C cristales · P el pilar
// Coordenadas en casillas (x, y). y crece hacia la cámara.
G.ZONES = {};

G.ZONES.gruta = {
  name: 'Gruta del Despertar', music: 'gruta', ambient: 'cueva',
  sky: '#4a5a8a', gnd: '#10141c', amb: 0.34, fog: '#04060a', fill: '#4a6080', fillI: 0.2, moss: 1.4, water: '#1ad0b8',
  look: { tint: [0.95, 1.0, 1.06], lift: [0.0, 0.01, 0.02], sat: 1.0, bloom: 1.0 },
  dust: { col: '#5a8a90', shaft: '#fff0d0', amount: 0.7 },
  shafts: [[6, 11, 18, '#ffeccc', 0.8]], spot: 1.8,
  rays: [[15, 5, 9, '#d8f0ff', 0.45], [21, 11, 7, '#d8f0ff', 0.35], [11, 13, 6, '#e8f4ff', 0.3]],
  fauna: { flies: 50, spores: 110, grillos: 5, polillas: 4, peces: 5, murcielagos: true, gotas: 0.7, flyCol: '#9affd8', sporeCol: '#6ae8ff', mistCol: '#203848' },
  map: [
    '############################',
    '############################',
    '######===######====#########',
    '#####=,DI=####=rrrr=########',
    '####=,,K,,,==,rRrVr,=#######',
    '###=,U,,,..,,,rrRrRr,=######',
    '##=,H,....A..,rVrr~..,,=####',
    '##=,,...~~~~..rr~~~..,,=####',
    '#=,Y...~~~~~~~~~~~~...,.::::',
    '#=,M..~~~~~~~~~~~~....,:::::',
    '#=,,.N.~~~~~~~~~~...A..,::::',
    '#=,,,.....~~~~.....,,,,=####',
    '##-,,H,..U.B....N,K,,,-#####',
    '###-,,Y,......,,,,,,,-######',
    '####-,,,,,H,,,U,,,,--#######',
    '#####--,,,,,,,,,,--#########',
    '#######---------############',
    '############################',
  ],
  start: [6, 11],
  exits: [{ x0: 27, y0: 8, x1: 27, y1: 10, to: 'aldea', tx: 1, ty: 13, dir: 'right' }],
  things: [
    { x: 11, y: 9, text: ['El agua brilla por dentro, como si guardara estrellas.', 'Tu reflejo te devuelve la mirada. No ves ninguna marca en tu piel.'] },
    { x: 7, y: 5, text: ['Hongos de luz. Laten despacio, como si respiraran.'] },
    { x: 3, y: 9, text: ['Un hongo enorme. Su luz no calienta, pero consuela.'] },
    { x: 16, y: 5, text: ['Hongos rojos. Su luz no se parece a la de los demás: late a destiempo.', 'Mejor no tocarlos.'] },
  ],
  triggers: [{ x0: 12, y0: 3, x1: 21, y1: 8, scene: 'zona_roja', once: 'zona_roja' }],
  corrupt: [[17, 5, 0.22, 5]],
};

G.ZONES.aldea = {
  name: 'Aldea Nhar', music: 'aldea', ambient: 'aldea',
  sky: '#6a6a9a', gnd: '#1a1418', amb: 0.4, fog: '#06060c', fill: '#806a60', fillI: 0.22, moss: 1.1, water: '#22c8c0',
  look: { tint: [1.04, 1.0, 0.96], lift: [0.01, 0.005, 0.0], sat: 1.05, bloom: 0.95 },
  dust: { col: '#a09080', shaft: '#fff0d0', amount: 0.8 },
  shafts: [[19, 14, 30, '#fff0d0', 0.75]], spot: 1.2,
  rays: [[8, 9, 10, '#ffe8c8', 0.5], [31, 8, 12, '#ffe8c8', 0.45], [26, 19, 9, '#ffe8c8', 0.4], [12, 20, 8, '#ffe8c8', 0.35]],
  fauna: { flies: 80, spores: 60, grillos: 10, polillas: 8, peces: 6, gotas: 0.3, flyCol: '#d8ff8a', sporeCol: '#fff0b0', mistCol: '#303040' },
  map: [
    '###################:::##################',
    '###################:::##################',
    '#################==:::==################',
    '###########=====,,:::,,======###########',
    '##########=,,H,,,,:::,,,,,K,,=##########',
    '#########=,,,,,,qqqCqqq,,,,,,,=#########',
    '########=,,A,,,qqqqqqqqq,,,A,,,=########',
    '#######=,,,,,,,,,,:::,,,,,,,,,,,=#######',
    '######=,T,,,,L,,,,:::,,,,L,,,,T,,=######',
    '#####=,,,,,,,,,,,,:::,,,,,,,,,,,,,=#####',
    '####=,,,,,,,,,,::::::::,,,,,,,,,,,,=####',
    '###=O,H,,,,,,,::,,,,,,::,,,,,,,,H,,,=###',
    '##=,,,,,,,,,:::,~~~~~~,:::,,,,,,,,,,,=##',
    '::::::::::::::,~~~~~~~~,:::::::,T,,,,,=#',
    '::::::,,,,,,,,,~~~~~~~~~,,,,,,,,,,,,,,,#',
    '::::,,,T,,,,,,,~~~~~~~~,,,,,,S,,,,,,,,,#',
    '##=,,,,,,,,,L,,,~~~~~~,,,,,L,,,,,,,,,,=#',
    '###-,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-##',
    '###-,,K,,,,wwwwww,,,,,,,,,,,,,T,,,,,-###',
    '####-,,,,,,wwwwww,,,,,,,,,,,,,,,,,,-####',
    '#####-,,,,,wwwwww,,,,,H,,,,,,,,,,,-#####',
    '######-,,,,,,,,,,,,,,,,,,,,,,,,,,-######',
    '#######--,,,,,,,,,,,,,,,,,,,,,,--#######',
    '#########-------------------------######',
    '########################################',
  ],
  exits: [
    { x0: 0, y0: 13, x1: 0, y1: 15, to: 'gruta', tx: 26, ty: 9, dir: 'left' },
    { x0: 19, y0: 0, x1: 21, y1: 0, to: 'senda', tx: 15, ty: 36, dir: 'up', need: 'permiso', block: 'guardia' },
  ],
  lights: [[20, 5, 20, '#ff3a60', 0.9, 90, 0.2]],
  npcs: [
    { id: 'mira', spr: 'mira', x: 9, y: 14, dir: 'right', talk: 'mira' },
    { id: 'suen', spr: 'suen', x: 30, y: 12, dir: 'left', talk: 'suen' },
    { id: 'aldeano1', spr: 'aldeano1', x: 22, y: 17, dir: 'down', talk: 'aldeano1', wander: 2 },
    { id: 'aldeano2', spr: 'aldeano2', x: 12, y: 19, dir: 'right', talk: 'aldeano2' },
    { id: 'aldeano3', spr: 'aldeano1', x: 27, y: 9, dir: 'down', talk: 'aldeano3', wander: 1.5 },
    { id: 'guardia', spr: 'guardia', x: 19, y: 8, dir: 'down', talk: 'guardia' },
    { id: 'varek', spr: 'varek', x: 21, y: 6, dir: 'down', talk: 'varek' },
  ],
  things: [
    { x: 19, y: 5, text: ['Un fragmento de cuarzo rojo sobre un altar de piedra.', 'Alguien ha dejado ofrendas alrededor: hongos secos, conchas, un collar de marcas pintadas.'] },
    { x: 19, y: 14, text: ['El Lago Nhar. Dicen que el Abismo habla más fuerte cerca del agua.', 'Tú solo oyes el goteo.'] },
  ],
  triggers: [{ x0: 1, y0: 13, x1: 3, y1: 15, scene: 'llegada_aldea', once: 'llegada' }],
};

G.ZONES.senda = {
  name: 'Senda de las Raíces', music: 'senda', ambient: 'pilar',
  sky: '#8a5a7a', gnd: '#1a0c12', amb: 0.36, fog: '#0a0408', fill: '#a06070', fillI: 0.2, moss: 1.3, water: '#c83a5a',
  look: { tint: [1.08, 0.96, 0.98], lift: [0.015, 0.0, 0.005], sat: 1.08, bloom: 1.1 },
  dust: { col: '#b07080', shaft: '#fff0e0', ember: '#ff4a6a', embers: 0.25, amount: 1 },
  shafts: [[14, 7, 40, '#fff2dc', 0.9]], spot: 1.5,
  rays: [[9, 25, 9, '#fff0e0', 0.45], [21, 19, 10, '#fff0e0', 0.4], [11, 16, 7, '#ffe0e8', 0.35]],
  fauna: { flies: 40, spores: 120, grillos: 6, polillas: 3, gotas: 0.3, flyCol: '#ffb0c0', sporeCol: '#ff6a8a', mistCol: '#401828' },
  corrupt: [[14, 7, 0.55, 22]], // (x, y, intensidad, radio): el aire se tuerce cerca del pilar
  map: [
    '##############################',
    '##############################',
    '#########^^^^^^^^^^^##########',
    '#######^^rrrrrrrrrrr^^########',
    '######^rrrVrrrrrrrVrrr^#######',
    '#####^rrCrrrqqqqqrrrCrr^######',
    '####^rrrrrrqqqqqqqrrrrrr^#####',
    '####^rVrrrqqqqPqqqqrrrVrr:::::',
    '####^rrrrrrqqqqqqqrrrrrrr:::::',
    '####^rrFrrrrqqqqqrrrrFrrr:::::',
    '#####^rrrrrrrrrrrrrrrrrr^#####',
    '######^rrrVrrr:::rrrVrrr^#####',
    '#######^^rrrrr:::rrrrr^^######',
    '#########==,rr:::rr,==########',
    '##########=,,r:::r,,=#########',
    '#########=,,,,:::,,,,=########',
    '########=,,H,,:::,,C,,=#######',
    '#######=,,,,,:::,,,,,,=#######',
    '######=,,,A,:::,,,,,,=########',
    '######=,,,,,:::,,,S,,=########',
    '######=,,,,,,:::,,,,,,=#######',
    '#######=,,K,,,:::,,,,,,=######',
    '########=,,,,,:::,,,V,,=######',
    '#########=,,,,:::,,,,,=#######',
    '#########=,,,,,:::,,,=########',
    '########=,,,,,,:::,,,,=#######',
    '#######=,,H,,,,:::,,,,,=######',
    '######=,,,,,,,,:::,,,,A,=#####',
    '######=,,A,,,,,:::,,,,,,=#####',
    '######=,,,,,,,,:::,,,H,,=#####',
    '#######=,,,,,,,:::,,,,,=######',
    '########=,,,,,,:::,,,,=#######',
    '#########-,,,,,:::,,,-########',
    '##########-,,O,:::,,-#########',
    '###########-,,,:::,-##########',
    '############-,,:::-###########',
    '############-,,:::-###########',
    '#############-,:::-###########',
    '##############-:::############',
  ],
  exits: [
    { x0: 15, y0: 38, x1: 17, y1: 38, to: 'aldea', tx: 20, ty: 1, dir: 'down' },
    { x0: 29, y0: 7, x1: 29, y1: 9, to: 'santuario', tx: 1, ty: 13, dir: 'right', need: 'tharn_libre', msg: 'El guardián del Claro te cierra el paso con la mirada.' },
  ],
  npcs: [
    { id: 'perdido', spr: 'infectado', x: 12, y: 23, dir: 'right', talk: 'perdido', wander: 1 },
    { id: 'tharn', spr: 'tharn', x: 15, y: 12, dir: 'down', talk: 'tharn', scale: 1.35, hideIf: 'tharn_libre' },
    { id: 'tharn2', spr: 'tharn_libre', x: 13, y: 12, dir: 'right', talk: 'tharn_libre', scale: 1.35, showIf: 'tharn_libre' },
  ],
  things: [
    { x: 14, y: 7, text: ['El pilar. Canta con una nota tan aguda que casi no se oye.', 'Por un momento crees recordar algo... pero no es tuyo.'] },
  ],
  triggers: [
    { x0: 12, y0: 30, x1: 19, y1: 31, scene: 'senda_roja', once: 'senda_roja' },
    { x0: 12, y0: 14, x1: 18, y1: 15, scene: 'tharn', once: 'tharn_visto', unless: 'tharn_libre' },
  ],
};

G.ZONES.santuario = {
  name: 'Santuario Hundido', music: 'gruta', ambient: 'santuario',
  sky: '#6a5a9a', gnd: '#140c18', amb: 0.34, fog: '#06040c', fill: '#8070b0', fillI: 0.22, moss: 1.2, water: '#7a6aff',
  look: { tint: [1.0, 0.97, 1.08], lift: [0.01, 0.0, 0.02], sat: 1.02, bloom: 1.15 },
  dust: { col: '#8a80c0', shaft: '#f0e8ff', ember: '#ff5a7a', embers: 0.12, amount: 1 },
  shafts: [[13, 5, 26, '#e8e0ff', 0.9]], spot: 1.6,
  rays: [[6, 13, 9, '#e8e0ff', 0.45], [19, 10, 8, '#e8e0ff', 0.4]],
  fauna: { flies: 40, spores: 100, grillos: 3, polillas: 4, peces: 4, murcielagos: true, gotas: 0.6, flyCol: '#c8b0ff', sporeCol: '#a8a0ff', mistCol: '#282040' },
  corrupt: [[13, 5, 0.35, 12]],
  map: [
    '##########################',
    '##########################',
    '########xx=====xx#########',
    '######xx==qqqqq==xx#######',
    '#####x==qqCqqqCqq==x######',
    '####x=qqqqqqqqqqqqq=x#####',
    '####=qqCqqqqqqqqqCqq=#####',
    '####=qqqqq..:..qqqqq=#####',
    '####=,,,,,..:..,,,,,=#####',
    '###=,,H,,...:...,,K,,=####',
    '###=,,,,~~~~:~~~~,,,,=####',
    '##=,,,,,~~~~:~~~~,,,,,=###',
    '##-,,O,,,,,,:,,,,,,A,,-###',
    '::::::::::::::,,,,,,,,-###',
    '::::,,S,,,,,,,,,,,H,,,-###',
    '##-,,,,,A,,,,,,,,,,,,-####',
    '###---,,,,,,,,,,,,,---####',
    '######-------------#######',
    '##########################',
  ],
  exits: [{ x0: 0, y0: 13, x1: 0, y1: 14, to: 'senda', tx: 28, ty: 8, dir: 'left' }],
  npcs: [
    { id: 'oren', spr: 'oren', x: 13, y: 5, dir: 'down', talk: 'oren', hideIf: 'oren_libre' },
    { id: 'oren2', spr: 'oren_libre', x: 13, y: 6, dir: 'down', talk: 'oren_libre', showIf: 'oren_libre' },
    { id: 'alma', spr: 'alma', x: 12, y: 12, dir: 'down', talk: 'alma', ghost: true, hideIf: 'almas' },
  ],
  things: [
    { x: 9, y: 7, text: ['Murales antiguos. Figuras con marcas brillantes rodean a otra, más pequeña, que no tiene ninguna.', 'Alguien ha rayado la cara de esa figura. Hace mucho tiempo.'] },
  ],
  triggers: [{ x0: 9, y0: 12, x1: 15, y1: 14, scene: 'alma', once: 'almas' }],
};
